Experiment saving and resumption
DAIRLab/dair_pll pull request #16
Opened 2023-03-29 14:35 UTC by mshalm

In #13, @ebianchi noted the value of restarting the often-lengthy training process in an experiment.

This PR implements saving and resuming experiments via the `dair_pll.experiment.TrainingState` dataclass.
Every epoch, `SupervisedLearningExperiment` saves this object to disk at `checkpoint.pt`, which includes

- Train/valid/test split as a list of indices, so training data can be re-apportioned correctly.
- Current learned system state; optimizer state; and epoch number so that the training process can be resumed at the right point.
- Best validation loss, as well as the learned system state that achieved it and the epoch it was achieved on, so that the training process can be properly stopped.

As part of correctly saving data, the functionality for generating simulation data has been separated from the process of loading from disk. This reflects the recent design change to consider multiple experiments as being based around the same dataset. Data generation also now saves both the raw trajectory from the underlying `System` (in `data/ground_truth`) _as well as_ the one with added measurement noise (in `data/learning`).

In order to keep the ballooning size of `experiment.py` down, configuration files have been migrated to `experiment_config.py` . For reproducibility, full configurations are also now pickled in `config.pkl` .

File loading and saving has been cleaned up as well, and the current folder structure is:
```
- storage/
  |
  - {storage_name}/
    |
    - data/
      | 
      - ground_truth/
      - learning/
    - runs/
      |
      - {run_name}/
        |
        - urdfs/
        - trajectory.gif
        - statistics.pkl
        - config.pkl
        - checkpoint.pt
        - wandb/
      - {other_run_name}/
        |
        - urdfs/
        - trajectory.gif
        - statistics.pkl
        - config.pkl
        - checkpoint.pt
        - wandb/
    - studies/
      |
      - {study_name}/
        |
        - optimal_hyperparameters.json
```

2023-03-31 19:16 UTC, ebianchi requested changes
This is going to be a very useful feature to have!  Overall I appreciate the thoughtful placement of each of the moving parts in this implementation, and testing it with `contactnets_simple.py` produced the expected outcomes.  I left some minor thoughts in comments.

One larger concern has to do with the local versus remote W&B storage and what happens if you try to reuse an experiment run name.  Though this may look like it could have been an issue starting with the move from Tensorboard to W&B (before this additional experiment saving and resumption functionality), it's actually a new issue now that `wandb.init` is called with `resume="allow"` as in this PR.

### Deeper description of the danger of reusing an experiment run name
You noted one potential issue that could arise from local versus remote W&B storage in a `Todo` comment in the class definition of `WeightsAndBiasesManager`.  However I've found another issue, and unfortunately a use case which could be fairly common and not just with a "crash at just the wrong time".  Here's a step-by-step way to reproduce the problem:

1. Create and start training an experiment run, with name `test_run`.
2. Stop the training process at epoch `n`.  Observe on the W&B run dashboard the progress of the learned parameters and loss, etc, through epoch `n`.
3. Clear the storage directory, then create and start an experiment run with the same name `test_run`.

At this point, the W&B run dashboard will still show the old results from the first time `test_run` was created through epoch `n`, then the new results starting with epoch `n+1`.  From the beginning, the command line will print `Resuming run test_run` and claim the results can be viewed on its dashboard, though all the new results through epoch `n` are ignored in favor of the old results.

Here's an example of some plots on the W&B run dashboard page when this happens.  The learning process made it through epoch 17 the first time the run was created.  Thus you'll see in all the below plots (except `cube_body_m` which coincidentally looks fairly smooth), there's a jump between epochs 17 and 18, since those don't actually correspond to the same training run.
![image](https://user-images.githubusercontent.com/29261567/229203949-ecdc38b7-aa1c-43fa-9854-5c2ffae70283.png)

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/dataset_generation.py
> +        n_to_add = 30
Is this just a convenient "batch size" for generating `n_to_add` trajectories at once?  Does this work better/faster than `n_to_add = max(n_pop - n_on_disk, 0)`?

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/dataset_management.py
> +        for time in range(first_time_index, last_time_index):
A small nit:  I always interpret the words "duration" and "time" to be in units of seconds(/days/years/etc).  Contrary to those expectations, here `trajectory_duration` is a number of time steps and `time` is an index number.  I'd personally prefer `trajectory_length` or `trajectory_time_steps`, and `time_index` or `index` just so the units are extra clear.

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/dataset_management.py
> +    n_sorted: int
It isn't immediately clear to me what `n_sorted` means.  A comment would be helpful here.  After looking at more of the code, it looks like it's a way to keep track of if:
- a dataset has been divvied up into train/valid/test sets, and
- a dynamic dataset has gotten an update and requires processing new trajectories.

The other attribute names are straightforward, but I'll leave it to you to decide whether to comment the other five for consistency.

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/dataset_management.py
> +        """s
Extraneous 's' or a placeholder?

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/dataset_management.py
> +                 initial_split: Optional[Tuple[Tensor, Tensor, Tensor]] = None,
It took me a while to realize these weren't actually the same thing, but here's my original interpretation: 
 The `config` already has attributes `train_fraction`, `valid_fraction`, and `test_fraction`, yet there's another argument here `initial_split` that implies the same information.  I see now that `initial_split` is a tuple of the actual indices of the dataset getting allotted to the train/valid/test sets, and not the fractions.  I think the variable names are fine, but interpretability could be aided by a function comment describing the `__init__` arguments.

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/dataset_management.py
> +        default_factory=TrajectorySliceConfig)
Comment description?

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/experiment.py
> +    """Which trajectories are in train/valid/test sets."""
Suggest including the word "indices" in "Which trajector[y indices] are in train/valid/test sets."

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/experiment.py
> -    data_manager: SystemDataManager
Why did the `data_manager` attribute get removed from this class?    Now it has to be an argument for the method `per_epoch_evaluation`, which used to just internally retrieve the saved attribute.

I'm not necessarily asking for a change here, I'm mostly curious about what is to me a non-intuitive update.

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/experiment.py
> +            validation loss.
Need to add comment for the newly-added `ExperimentDataManager` output argument.

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/experiment.py
> +                    data_manager: ExperimentDataManager) -> StatisticsDict:
Function comment needs to list the newly added `data_manager` argument.

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/file_utils.py
> +def load_binary(filename: str, load_callback: Callable[[BinaryIO], Any]) -> Any:
Is there a reason this has `load_callback` as an argument, as opposed to just internally using `pickle.load` since that's the only thing that gets passed into these function calls?  Unlike the new `load_string()` function, `load_binary()` doesn't do anything differently based on what gets passed into `loss_callback`.

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/file_utils.py
> +                save_callback: Callable[[Any, BinaryIO], None]) -> None:
Same thought about whether `save_callback` should get eliminated and the function could just use `pickle.dump` internally.

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/multibody_learnable_system.py
> +            file_utils.save_string(new_urdf_path, new_urdf_string)
This (and a similar spot in `urdf_utils.py` that wrote a string) is a great cleanup!

2023-03-31 19:16 UTC, ebianchi commented on examples/contactnets_simple.py
> +TRAJECTORY_DURATIONS = {CUBE_SYSTEM: 80, ELBOW_SYSTEM: 120}
Another location where "duration" is used to describe a number of time steps, as opposed to what is my interpretation of a duration as a length of time (in time units).

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/study.py
These changes look fine upon inspection, though I'm documenting here that I haven't tested this file, since it's currently a WIP.

2023-03-31 19:16 UTC, ebianchi commented on dair_pll/wandb_manager.py
> +        """
Putting an in-line comment here to flag the warning statement about a W&B issue, related to a worse one I describe in more detail in the overall review comment.

2023-04-01 19:49 UTC, mshalm commented on dair_pll/dataset_generation.py
> +        n_to_add = 30
It's to periodically save progress, especially for `n_pop` that would take a long time to compute (e.g. hours).

To aid in understanding, I will move `30` to a module member variable with an interpretable name and comment.

2023-04-01 20:16 UTC, mshalm commented on dair_pll/dataset_management.py
> +                 initial_split: Optional[Tuple[Tensor, Tensor, Tensor]] = None,
On my local storage I'm seeing that `__init__` already has comments, but from this discussion I don't think the `initial_split` comment is particularly clear, so I'll update it.

2023-04-01 20:21 UTC, mshalm commented on dair_pll/experiment.py
> -    data_manager: SystemDataManager
Yeah, in retrospect, an unhelpful/unnecessary change. Will revert.

2023-04-01 20:42 UTC, mshalm commented on dair_pll/file_utils.py
> +def load_binary(filename: str, load_callback: Callable[[BinaryIO], Any]) -> Any:
It's true that pickle files are the only binary files we load manually at the moment. I'm content to leave it as-is to have some structure for when/if there may be other types of binary files we want to load. But if you feel strongly I'm fine refactoring to a reasonable instance of `load_pickle`

2023-04-01 20:45 UTC, mshalm commented on dair_pll/dataset_management.py
> +    n_sorted: int
Added some documentation here

2023-04-03 16:31 UTC, mshalm commented
All comments addressed in the latest commits.

The biggest design change was made to address W&B's inability to start runs with the same name as a previously deleted run.

To compensate for this, the `wandb` training run ID is related to the `dair_pll` experiment `run_name` by
```
wandb_run_id = f"{run_name}_{time.time_ns()}"
```
where the timestamp comes from the time the run was started. This label is added to the `TrainingState` to enable restarting partially completed W&B runs.

2023-04-04 00:10 UTC, ebianchi commented on dair_pll/file_utils.py
> +def load_binary(filename: str, load_callback: Callable[[BinaryIO], Any]) -> Any:
I don't feel strongly -- your reasoning makes sense, so let's leave it as-is.

2023-04-04 00:12 UTC, ebianchi approved these changes
Everything looks good and works as expected.  Great improvement to add the timestamp to the end of the `wandb` IDs to elegantly restart old versus create new experiment runs.  All approved on my end.

2023-04-04 15:39 UTC, merged